version: "3.8"

services:
  web:
    command: yarn web dev
    build:
      context: ../../
      dockerfile: docker/coops-dev/Dockerfile
      target: "web"
    working_dir: /app
    env_file: "../../services/web/.env.local"
    ports:
      - 3000:3000
    volumes:
      - ../../services/web/src:/app/services/web/src
      - ../../services/web/public:/app/services/web/public
  peer:
    image: peerjs/peerjs-server
    command: --port 9000 --path /
    ports:
      - 9000:9000