version: "3.8"

services:
  nginx:
    image: nginx:1.21.0-alpine
    volumes:
      - ../../templates:/etc/nginx/templates
    ports:
      - 3000:80
  web:
    command: yarn web dev
    build:
      context: ../../
      dockerfile: Dockerfile
      target: "web"
      args:
        ENV: development
    working_dir: /app
    env_file: "../../services/web/.env.local"
    volumes:
      - ../../services/web/src:/app/services/web/src
      - ../../services/web/public:/app/services/web/public
  sse:
    command: node ./services/sse/dist/index.js
    build:
      context: ../../
      dockerfile: Dockerfile
      target: "sse"
      args:
        ENV: development
    working_dir: /app
  peer:
    image: peerjs/peerjs-server
    command: --port 9000 --path /peer
  redis:
    image: redis:6.2.3-alpine
  redis-commender:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081